spring:
  # JWT key 설정
  jwt:
    secret: KimdddsIdDidkSidjdpSJd937sdjdfjKJFudDjksdfdfi435k34tjHDKHd8iudsfFHkf8D8fKF9FDkl43ewlsdaf8dsafjk23KDF99dfF8fd6FDjDFasdfkkweqrk89DFuhsdfklsdaf98sdf98FDS89dfsjkHJK98DS98KFHD

  # Gmail SMTP Server Settings
  mail:
    host: smtp.gmail.com
    port: 587
    username: s19066@gsm.hs.kr
    password: iiqrerusxvwowahk
    properties:
      mail:
        smtp:
          timeout: 9999
          auth: true
          starttls:
            enable: true