spring:
  # JWT key 설정
  jwt:
    secret: goelepel@%&*(&(*&()^%&^*jhadsklfh*&^*&(^ds8af76(*&^ads8fsadf879asd6f*(A&^AFSads987f6asd897f6(*&ASF^ads9876fsad897f6(A*&SF^ads897fg6asd9f876*(&AFS^ads987gf6adfs8976

  # Gmail SMTP Server Settings
  mail:
    host: smtp.gmail.com
    port: 587
    username: s19066@gsm.hs.kr
    password: iiqrerusxvwowahk
    properties:
      mail:
        smtp:
          timeout: 9999
          auth: true
          starttls:
            enable: true