# 기본 설정
server:
  port: 8082
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  profiles:
    active: dev

  prometheus:
    name: actuator
    password: ksh03050621!
    role: prometheus-user

  jwt:
    secret: KimdddsIdDidkSidjdpSJd937sdjdfjKJFudDjksdfdfi435k34tjHDKHd8iudsfFHkf8D8fKF9FDkl43ewlsdaf8dsafjk23KDF99dfF8fd6FDjDFasdfkkweqrk89DFuhsdfklsdaf98sdf98FDS89dfsjkHJK98DS98KFHD

    # Gmail SMTP Server Settings
  mail:
    host: smtp.gmail.com
    port: 587
    username: s19066@gsm.hs.kr
    password: iiqrerusxvwowahk
    properties:
      mail:
        smtp:
          timeout: 9999
          auth: true
          starttls:
            enable: true

  # 데이터 베이스 설정
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  datasource:
    url: jdbc:h2:mem:chwijuntime
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
        hbm2ddl:
          auto: create
    show-sql: true
    open-in-view: false

#  # 데이터 베이스 설정
#  datasource:
#    url: jdbc:mysql://210.217.243.3:3306/chwijuntime
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: remoteuser
#    password: ksh03050621
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    show-sql: true
#    generate-ddl: true
#    database: mysql
#    properties:
#      hibernate:
#        temp:
#          use_jdbc_metadata_defaults: false
#        hbm2ddl:
#          auto: none

  #Redis
  cache:
    type: redis
    jcache:
      config: classpath:ehcache.xml
  redis:
    host: localhost
    port: 6379
  data:
    redis:
      repositories:
        enabled: false

  # i18n (에러 다국어 처리)
  messages:
    basename: i18n/exception
    encoding: UTF-8
  mvc:
    hiddenmethod:
      filter:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

logging:
  level:
    org:
      springframework:
        security: DEBUG
---

spring:
  profiles: real

  prometheus:
    name: actuator
    password: ksh03050621!
    role: prometheus-user

  jwt:
    secret: KimdddsIdDidkSidjdpSJd937sdjdfjKJFudDjksdfdfi435k34tjHDKHd8iudsfFHkf8D8fKF9FDkl43ewlsdaf8dsafjk23KDF99dfF8fd6FDjDFasdfkkweqrk89DFuhsdfklsdaf98sdf98FDS89dfsjkHJK98DS98KFHD

    # Gmail SMTP Server Settings
  mail:
    host: smtp.gmail.com
    port: 587
    username: s19066@gsm.hs.kr
    password: iiqrerusxvwowahk
    properties:
      mail:
        smtp:
          timeout: 9999
          auth: true
          starttls:
            enable: true

    # 데이터 베이스 설정
  datasource:
    url: jdbc:mysql://210.217.243.3:3306/chwijuntime
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: remoteuser
    password: ksh03050621
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    generate-ddl: true
    database: mysql
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        hbm2ddl:
          auto: none

  #Redis
  cache:
    type: redis
    jcache:
      config: classpath:ehcache.xml
  redis:
    host: 210.217.243.3
    port: 6379
  data:
    redis:
      repositories:
        enabled: false

  # i18n (에러 다국어 처리)
  messages:
    basename: i18n/exception
    encoding: UTF-8
  mvc:
    hiddenmethod:
      filter:
        enabled: true

bucket4j:
  enabled: true
  filters[0]:
    cache-name: buckets
    filter-method: servlet
    url: .*
    filters[0]:
      rate-limits[0]:
        bandwidths[0]:
          capacity: 10
          time: 1
          unit: minutes
          fixed-refill-interval: 0
          fixed-refill-interval-unit: minutes
        expression: getRemoteAddress()

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

logging:
  level:
    org:
      springframework:
        security: DEBUG